scale expectation add time
openkruise/kruise pull request #403
Opened 2020-10-14 07:36 UTC by hellolijj

Signed-off-by: JunjunLi <junjunli666@gmail.com>

### Ⅰ. Describe what this PR does

scale expectation add time

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2020-10-14 08:00 UTC, furykerry commented on pkg/util/expectations/scale_expectations.go
> +	lastUnsatisfiedTimestamp time.Time
when lastUnsatisfiedTimestamp is initialized ?

2020-10-14 08:00 UTC, furykerry commented on pkg/controller/cloneset/cloneset_controller.go
> +		if time.Now().Sub(clonesetutils.ScaleExpectations.GetLastUnsatisfiedTimestamp()) == time.Minute {
time.Now().Sub() equals to time.Since(), which is more clear

2020-10-15 02:02 UTC, FillZpp requested changes

2020-10-15 02:02 UTC, FillZpp commented on pkg/util/expectations/scale_expectations.go
> +	lastUnsatisfiedTimestamp time.Time
Should not define `lastUnsatisfiedTimestamp ` here, because `realScaleExpectations` is a global cache.

2020-10-20 02:33 UTC, FillZpp requested changes

2020-10-20 02:33 UTC, FillZpp commented on pkg/controller/cloneset/cloneset_controller.go
> +	if scaleSatisfied, timeout, scaleDirtyPods := clonesetutils.ScaleExpectations.SatisfiedExpectations(request.String()); !scaleSatisfied {
`timeout ` -> `unsatisfiedDuration`

2020-10-20 02:33 UTC, FillZpp commented on pkg/controller/cloneset/cloneset_controller.go
> +			klog.Warningf("Expectation unsatisfied overtime for %v, scaleDirtyPods=%v, overtime=%v", request.String(), scaleDirtyPods, timeout)
`overtime` -> `timeout`

2020-10-20 02:33 UTC, FillZpp commented on pkg/util/expectations/init.go
> +	flag.DurationVar(&ExpectationTimeout, "expectation-timeout", ExpectationTimeout, "The expectation timeout.")
This will lead to default timeout 0

2020-10-20 02:33 UTC, FillZpp commented on pkg/util/expectations/resource_version_expectation.go
> +	firstUnsatisfiedTimestamp time.Time
`firstUnsatisfiedTimestamp` should not put in global realResourceVersionExpectation

2020-10-22 02:53 UTC, FillZpp approved these changes
LGTM

2020-10-22 02:53 UTC, merged