add assign-bcj-pods-by-scheduler flag for bcj
openkruise/kruise pull request #498
Opened 2020-12-28 11:59 UTC by devincd

### Ⅰ. Describe what this PR does
add assign-bcj-pods-by-scheduler flag for bcj, bcj needs to go to Kubernetes scheduler by default

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-01-07 09:23 UTC, FillZpp requested changes
@devincd Could you please fix the `gofmt`, run `make generate manifests`, squash commits and force push again?

2021-01-07 09:23 UTC, FillZpp commented on pkg/controller/broadcastjob/broadcastjob_controller.go
> +		if len(nodeName) != 0 {
File is not `gofmt`-ed with `-s` (gofmt)

2021-01-08 02:43 UTC, devincd commented
> @devincd Could you please fix the `gofmt`, run `make generate manifests`, squash commits and force push again?

done

2021-01-08 03:10 UTC, FillZpp approved these changes
LGTM

2021-01-08 03:10 UTC, merged