Optimize the calculation algorithm for CloneSet scaling and updating
openkruise/kruise pull request #562
Opened 2021-03-15 09:22 UTC by FillZpp

Signed-off-by: FillZpp <FillZpp.pub@gmail.com>

### Ⅰ. Describe what this PR does
Optimize the calculation algorithm for CloneSet scaling and updating.

Code changes:
1. The `scale` and `update` packages have been amalgamated into `sync` package, which includes the main logic of cloneset reconciling.
2. The `calculateDiffsWithExpectation` function is the most important algorithm in cloneset controller. It calculates the pod numbers to scaling and updating for current CloneSet.

Behavior changes:
1. After increasing partition during canary update, the old cloneset controller will do nothing, but now the controller will rollback pods with **updateRevision** to **currentRevision**.
2. When deleting Pods via specified or replicas, the old cloneset controller will delete them immediately, but now the controller will delete Pods according to maxUnavailable and maxSurge.

### Ⅱ. Does this pull request fix one issue?

fixes #451 
fixes #410 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
pkg/controller/cloneset/sync/cloneset_sync_utils_test.go

### Ⅳ. Describe how to verify it
1. Increase partition during canary update
2. Specified delete pods in a CloneSet with maxSurge and maxUnavailable

2021-03-16 22:45 UTC, Fei-Guo commented on pkg/controller/cloneset/sync/cloneset_sync_utils.go
> +func calculateDiffsWithExpectation(cs *appsv1alpha1.CloneSet, pods []*v1.Pod, updateRevision string) (res expectationDiffs) {
I suggest to have a separate document to explain the algorithm. I think code comments are not enough to explain the intentions well. When user observed behaviors that are out of their expectations, they need to have a reference to justify the observations.

2021-03-25 07:15 UTC, furykerry requested changes

2021-03-25 07:15 UTC, furykerry commented on pkg/controller/cloneset/sync/cloneset_sync_utils.go
> +	scaleDiff int
scaleDiff -> scaleIn

scalediff make me very frustrated about the exact direction of scaling, scaleIn can be more clear

2021-03-25 07:15 UTC, furykerry commented on pkg/controller/cloneset/sync/cloneset_sync_utils.go
> +	updateDiff int
updateDiff -> updateNum

2021-03-25 07:15 UTC, furykerry commented on pkg/controller/cloneset/sync/cloneset_sync_utils.go
> +	scaleOldRevisionDiff int
scaleOldRevisionDiff -> scaleInOldRevision

2021-03-25 07:15 UTC, furykerry commented on pkg/controller/cloneset/sync/cloneset_update.go
> +	sort.Slice(waitUpdateIndexes, func(i, j int) bool {
what is the relative weights of different sort criteria: PriorityStrategy , ScatterStrategy and GetPodLifecycleState?
Is it better to use stable sort (slice -> sliceStable) here ?
please describe them in the func comments.

2021-03-25 07:15 UTC, furykerry commented on pkg/controller/cloneset/sync/cloneset_update.go
> +func limitUpdateIndexes(coreControl clonesetcore.Control, minReadySeconds int32, diffRes expectationDiffs, waitUpdateIndexes []int, pods []*v1.Pod) []int {
please describe the limitation criteria and return values

2021-03-25 11:25 UTC, furykerry approved these changes

2021-03-25 11:25 UTC, merged