Proposal: cascading deletion protection
openkruise/kruise pull request #577
Opened 2021-03-31 10:54 UTC by FillZpp

Signed-off-by: FillZpp <FillZpp.pub@gmail.com>

### Ⅰ. Describe what this PR does
Proposal: cascading deletion protection

Kruise should provide a safety policy which could help users protect Kubernetes resources and applications' availability from the cascading deletion mechanism.

2021-04-01 03:09 UTC, furykerry requested changes

2021-04-01 03:09 UTC, furykerry commented on docs/proposals/20210331-cascadingdeletionprotection.md
> +If users enable `ResourcesDeletionProection` feature-gate when install or upgrade Kruise,
typo: ResourcesDeletionProection -> ResourcesDeletionProtection

2021-04-01 03:09 UTC, furykerry commented on docs/proposals/20210331-cascadingdeletionprotection.md
> +2. ClusterRole for reading all resource types, because CRD validation needs to list the CRs of this CRD.
Is it possible to add a feature gate for CustomResourceDefinition protection? privilege for all resource types are just so huge. we can protect the kruise crd only by default

2021-04-27 17:26 UTC, Fei-Guo commented
LGTM

2021-05-17 09:09 UTC, furykerry approved these changes

2021-05-17 09:09 UTC, merged