Add proposal of UnitedTopology, a bypass scheme for elasticity and multi-domain management
openkruise/kruise pull request #613
Opened 2021-04-27 08:01 UTC by FillZpp

Signed-off-by: FillZpp <FillZpp.pub@gmail.com>

### Ⅰ. Describe what this PR does
Add proposal of UnitedTopology, a bypass scheme for elasticity and multi-domain management

### Ⅴ. Special notes for reviews
UnitedTopology supports configuration and management for elastic and multi-domain applications,
even more powerful and flexible than UnitedDeployment in some ways.

Not like the workload type, UnitedTopology can be used with those stateless workloads, such as CloneSet, Deployment and ReplicaSet.

So users needn't learn the usage of a new workload and how to deploy and update their application by it.
They only have to create UnitedTopology CRs related to their existing workloads.

2021-04-27 17:55 UTC, Fei-Guo reviewed
I understand the intention and I think it is a good idea. 

UnitedTopology does not sound clear for what the controller will do. It is essentially a workload Pod distribution manager that influences the scheduling results. 

So I would suggest to change CRD name to a more explicit one, such as WorkloadDistribution/PodDistribution/TopologyTrack etc.

2021-04-27 18:01 UTC, Fei-Guo commented on docs/proposals/20210427-unitedtopology.md
> +  - `adaptive`:
The `adaptive` strategy and the `adaptive` type look duplicated concepts.

I would suggest to remove the `adaptive` strategy in the first version. It seems that 
the  `rescheduleCriticalSeconds` can be hard coded in the beginning. 
The `disableSimulationSchedule` needs explanation which seems to be optional in most cases.

2021-04-27 18:04 UTC, Fei-Guo commented
One more thing - it will great to compare this proposal with K8s PodTopologySpread API so that people can understand why we want to enhance the upstream scheduling API.

2021-06-01 07:23 UTC, furykerry requested changes

2021-06-01 07:23 UTC, furykerry commented on docs/proposals/20210427-unitedtopology.md
> +- `subsets`: list of subsets which defines different topologies
comments about the order of topology which may influence creation and deletion order

2021-06-01 07:23 UTC, furykerry commented on docs/proposals/20210427-unitedtopology.md
> +1. `Guaranteed` for Pods that in the `maxReplicas` of its subset, deletion-cost will be set bigger than `0`
consider the case that deployments with idc and cloud instance, we may prefer to delete cloud instance even without maxReplicas

2021-06-25 06:13 UTC, FillZpp commented
There will be a new PR for this proposal.

2021-06-25 06:13 UTC, closed without merging