podunavailablebudget proposal
openkruise/kruise pull request #646
Opened 2021-06-15 03:34 UTC by zmberg

Signed-off-by: liheng.zms <liheng.zms@alibaba-inc.com>

### Ⅰ. Describe what this PR does
- In voluntary disruption scenarios, PodUnavailableBudget can achieve the effect of preventing application disruption or SLA degradation, which greatly improves the high availability of application services.

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-06-15 06:49 UTC, furykerry requested changes

2021-06-15 06:49 UTC, furykerry commented on docs/proposals/20210614-podunavailablebudget.md
> +2. When upgrading the application version, all pods are restarted at the same time due to the wrong configuration of the rolling upgrade policy, for example MaxUnavailable=0
even if the user correctly set maxUnavailable in the workload, there is still cases where availability is hampered. For example when workload rolling upgrade and voluntary eviction of pods are both running. The key reason we use PUB is maxUnavailable in workload or PDB cannot protect simultaneous modification of pods. So I think we should hight light such user cases, and do not focus on the un-intentional workload deletion or ill-configured workload.

2021-06-15 06:49 UTC, furykerry commented on docs/proposals/20210614-podunavailablebudget.md
> +	TargetReference *TargetReference `json:"targetRef,omitempty"`
please comments about when target reference is required when we already have selector fields

2021-06-15 06:49 UTC, furykerry commented on docs/proposals/20210614-podunavailablebudget.md
> +```
please explain the pub status fields

2021-06-15 06:49 UTC, furykerry commented on docs/proposals/20210614-podunavailablebudget.md
> +2. PUB validating is based on the kubernetes admission webhook mechanism, which decides whether to allow this operation to be executed based on the UnavailableAllowed in the PUB Status:
can we elaborate the data manipulation of pub status here ?

2021-06-17 02:25 UTC, furykerry requested changes

2021-06-17 02:25 UTC, furykerry commented on docs/proposals/20210614-podunavailablebudget.md
> +2. The middleware team is using [SidecarSet](https://openkruise.io/en-us/docs/sidecarset.html) to rolling upgrade the sidecar containers of the cluster, e.g. ServiceMesh envoy, while HPA triggers the
plz add the case for pod eviction initiated by admin, pod eviction is a more general case which occurs even if no kruise workload is used.

2021-06-17 02:25 UTC, furykerry commented on docs/proposals/20210614-podunavailablebudget.md
> +	// UnavailablePods contains information about pods whose specification changed(inplace-update pod),
specification changes does not necessarily means inplace-update, pod container restart is also possible. plz changes to 
(e.g. inplace-update)

2021-06-17 02:25 UTC, furykerry commented on docs/proposals/20210614-podunavailablebudget.md
> +	// processed by the API handler but has not yet been observed by the PodUnavailableBudget.
> has not yet been observed by the PodUnavailableBudget
has not yet been observed by the PodUnavailableBudget controller

2021-06-18 09:16 UTC, furykerry reviewed
LGTM

2021-06-23 07:33 UTC, Fei-Guo commented
LGTM

2021-06-28 02:02 UTC, furykerry approved these changes

2021-06-28 02:02 UTC, merged