podunavailablebudget controller
openkruise/kruise pull request #669
Opened 2021-07-12 13:23 UTC by zmberg

Signed-off-by: liheng.zms <liheng.zms@alibaba-inc.com>

### Ⅰ. Describe what this PR does
podunavailablebudget controller calculate and maintain status

### Ⅱ. Does this pull request fix one issue?

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2021-07-12 18:42 UTC, Fei-Guo commented
/lgtm

2021-07-13 08:45 UTC, FillZpp commented on pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
> +	err = c.Watch(&source.Kind{Type: &policyv1alpha1.PodUnavailableBudget{}}, &handler.EnqueueRequestForObject{}, predicate.GenerationChangedPredicate{})
Are you sure to use `predicate.GenerationChangedPredicate`? It may skip to add the PUB into workqueue when its status has been updated by webhook.

2021-07-13 08:45 UTC, FillZpp commented on pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
> +		return ctrl.Result{RequeueAfter: recheckTime.Sub(time.Now())}, nil
use time.Until instead of t.Sub(time.Now())

2021-07-13 12:49 UTC, zmberg commented on pkg/controller/podunavailablebudget/pub_controller_test.go
> +	"sigs.k8s.io/controller-runtime/pkg/client/fake"
ignore

2021-07-13 12:51 UTC, zmberg commented on pkg/controller/podunavailablebudget/pub_pod_event_handler_test.go
> +	"sigs.k8s.io/controller-runtime/pkg/client/fake"
ignore

2021-07-28 10:21 UTC, furykerry requested changes

2021-07-28 10:21 UTC, furykerry commented on pkg/controller/cloneset/sync/cloneset_update.go
> +		allowed, err := pubcontrol.ValidateInPlacePodForPub(c.Client, pod)
is it possible to validate pods in batch to reduce overhead such as pub listing

2021-07-28 12:38 UTC, zmberg commented on pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
> +			minAvailable, err = intstr.GetValueFromIntOrPercent(pub.Spec.MinAvailable, int(expectedCount), true)
maxUnavailable round down, and MinAvailable round up?

2021-08-02 02:41 UTC, furykerry commented
/lgtm

2021-08-04 04:23 UTC, furykerry commented
/lgtm

2021-08-04 04:24 UTC, furykerry commented
/approve

2021-08-04 05:05 UTC, FillZpp approved these changes

2021-08-04 05:11 UTC, merged